image: alpine:3.9

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build ubuntu:
  stage: build
  script: bash buildubuntu.sh

before_script:
  - apk add emscripten make --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing

build web:
  stage: build
  script: bash buildweb.sh
